1. Import numpy as np

In [6]:
import numpy as np

2. Create an array of 10 zeros

In [7]:
arr = np.zeros(10)

3. Create an array of 10 ones

In [8]:
arr2 = np.ones(10)

In [9]:
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4. Create an of 10 fives 

In [10]:
arr3 = np.ones(10)*5

In [11]:
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. Create an array of the integers from 10 to 50

In [12]:
arr4 = np.arange(10, 51)

In [13]:
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6. Create an array of all the even integers from 10 to 50

In [14]:
arr4[arr4 % 2 == 0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7. Create a 3X3 matrix with values ranging from 0 to 8

In [15]:
arr5 = np.arange(0,9).reshape(3, 3)

In [16]:
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8. Createa 3X3 identity matrix

In [17]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9. Use numpy to generate a random number between 0 and 1

In [18]:
from numpy.random import randint, randn, rand

In [19]:
rand(1)

array([0.79167166])

10. Use numpy to generate an array of 25 random numbers sampled
from a standard normal distribution

In [20]:
randn(25)

array([-0.37585653,  2.80357799, -0.00446459,  0.28557752, -0.73111345,
       -0.03410863, -0.81331729, -0.1814716 ,  0.38825775, -0.60060678,
        0.02173184,  0.08417329,  0.66358681, -0.94085509, -0.38586976,
        1.49173759, -0.56687836, -0.14829972, -1.30846261, -1.2614037 ,
        0.13649682,  0.07754833,  1.16448468, -0.21802771,  0.37097427])

11. Create the following matrix (Look the output)

In [21]:
arr8 = np.arange(0.01, 1.01, 0.01).reshape(10, 10)

In [22]:
arr8

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

12. Create an array of 20 linearly spaced points between 0 and 1

In [23]:
arr9 = np.linspace(0, 1, 20)

In [24]:
arr9

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

 NUMPY INDEXING AND SELECTION EXERCISES

In [25]:
mat = np.arange(1, 26).reshape(5,5)

In [26]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

1. Write a code that reproduces the output below

In [27]:
mat[2:5, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [28]:
 mat[3][4]

20

In [29]:
mat[0:3, 1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [30]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
np.sum(mat)

325

In [32]:
np.std(mat)

7.211102550927978

In [33]:
mat.sum(axis=0)#sum of columns

array([55, 60, 65, 70, 75])

In [34]:
mat.sum(axis=1) #sum of rows

array([ 15,  40,  65,  90, 115])

In [35]:
#EXERCISES NAILED!!!!!!! GOOD JOB!